/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

/**
 *
 * @author kevin
 */
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import metodos.Juego;
import metodos.Problema;

public class ModoPoner extends javax.swing.JPanel {

    /**
     * Creates new form ModoPonerr
     */
    private final JPanel c;
    private Problema problema;
    private int correcto;

    private void Image(String URL, JLabel l, int ancho, int alto) {
        Image j = Toolkit.getDefaultToolkit().getImage(getClass().getResource(URL));
        l.setIcon(new ImageIcon(j.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH)));
    }

    public ModoPoner(JPanel c) {
        this.c = c;
        initComponents();

        Image("/img/006.png", jack, 400, 400);

        cargarProblema();
    }

    public void cargarProblema() {
        problema = Juego.getInstancia().nextProblema();

        sumando1.setText(problema.getSumando1() + "");
        sumando2.setText("?");
        operador.setText(problema.getOperandor() + "");
        respuesta.setText(problema.getRespuesta() + "");

    }

    private void page(JPanel i, JPanel c) {
        i.setSize(c.getWidth(), c.getHeight());
        i.setLocation(0, 0);

        c.removeAll();
        c.add(i);
        c.revalidate();
        c.repaint();
    }

    private void PosSelecion() {
        Image("/img/005.png", jack, 400, 400);
    }

    private void DesSelecion() {
        Image("/img/006.png", jack, 400, 400);
    }

    public void ComenzarJuego() {
        Juego juego = new Juego();
        int n = juego.getProblemasDeTipoPoner().size();
    }

    private void evaluar() {
        correcto = Integer.parseInt(posible1.getText());
        if (correcto == problema.getSumando2()) {
            abrirCorrectoPag();
        } else {
            abrirIncorrectoPag();
        }
    }

    private void abrirCorrectoPag() {
        Juego.getInstancia().SistemaDePuntos(5);
        Acierto a = new Acierto(c);
        page(a, c);
    }

    private void abrirIncorrectoPag() {
        Juego.getInstancia().SistemaDePuntos(2);
        Fallo f = new Fallo(c);
        page(f, c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        posible1 = new javax.swing.JTextField();
        jack = new javax.swing.JLabel();
        puntos = new javax.swing.JLabel();
        operador = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sumando2 = new javax.swing.JLabel();
        sumando1 = new javax.swing.JLabel();
        sumando3 = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        acceptar = new javax.swing.JButton();
        respuesta = new javax.swing.JLabel();
        omitir = new javax.swing.JLabel();
        puntero = new javax.swing.JLabel();

        setBackground(new java.awt.Color(149, 184, 246));

        posible1.setBackground(new java.awt.Color(149, 184, 246));
        posible1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        posible1.setForeground(new java.awt.Color(255, 255, 255));

        jack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/006.png"))); // NOI18N

        puntos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        puntos.setForeground(new java.awt.Color(255, 255, 255));
        puntos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntos.setText("Puntos :");

        operador.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        operador.setForeground(new java.awt.Color(255, 255, 255));
        operador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        operador.setText("+");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("=");

        sumando2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        sumando2.setForeground(new java.awt.Color(255, 255, 255));
        sumando2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sumando2.setText("?");

        sumando1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        sumando1.setForeground(new java.awt.Color(255, 255, 255));
        sumando1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sumando1.setText("5");

        sumando3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        sumando3.setForeground(new java.awt.Color(255, 255, 255));
        sumando3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sumando3.setText("?");

        salir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText("salir");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("=");

        texto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto.setText("Escribe la respuesta correcta");

        acceptar.setBackground(new java.awt.Color(102, 153, 255));
        acceptar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        acceptar.setForeground(new java.awt.Color(255, 255, 255));
        acceptar.setText("aceptar");
        acceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acceptarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                acceptarMouseEntered(evt);
            }
        });

        respuesta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        respuesta.setForeground(new java.awt.Color(255, 255, 255));
        respuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        respuesta.setText("10");

        omitir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        omitir.setForeground(new java.awt.Color(255, 255, 255));
        omitir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        omitir.setText("omitir");
        omitir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                omitirMouseClicked(evt);
            }
        });

        puntero.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        puntero.setForeground(new java.awt.Color(255, 255, 255));
        puntero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        puntero.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jack, javax.swing.GroupLayout.PREFERRED_SIZE, 228, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sumando3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sumando1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(operador, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sumando2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(posible1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(249, 249, 249))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(acceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(omitir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(puntos, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(puntero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puntero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jack, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(omitir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sumando3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sumando2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(operador, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sumando1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(109, 109, 109)
                                .addComponent(posible1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(acceptar)))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        ModoDeJuego m = new ModoDeJuego(c);
        page(m, c);
    }//GEN-LAST:event_salirMouseClicked

    private void acceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptarMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_acceptarMouseEntered

    private void omitirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_omitirMouseClicked
        // TODO add your handling code here:
        if (!Juego.getInstancia().isJuegoTerminado()) {
            cargarProblema();
        } else {
            Juego.getInstancia().terminarJuego();
            ModoRanking m = new ModoRanking(c);
            page(m, c);
        }
    }//GEN-LAST:event_omitirMouseClicked

    private void acceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptarMouseClicked
        // TODO add your handling code here:
        evaluar();
    }//GEN-LAST:event_acceptarMouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jack;
    private javax.swing.JLabel omitir;
    private javax.swing.JLabel operador;
    private javax.swing.JTextField posible1;
    private javax.swing.JLabel puntero;
    private javax.swing.JLabel puntos;
    private javax.swing.JLabel respuesta;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel sumando1;
    private javax.swing.JLabel sumando2;
    private javax.swing.JLabel sumando3;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables

}
