/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import metodos.Juego;

/**
 *
 * @author Josue
 */
public class ModoDeJuego extends javax.swing.JPanel {

    /**
     * Creates new form ModoDeJuego
     */
    private final JPanel c;
    

    public ModoDeJuego(JPanel c) {
        initComponents();
        this.c = c;

        Image("/img/007.png", jack, 350, 350);
        Image("/img/009.png", f1, 250, 200);
        Image("/img/009.png", f2, 250, 200);

    }

    private void page(JPanel i, JPanel c) {
        i.setSize(c.getWidth(), c.getHeight());
        i.setLocation(0, 0);

        c.removeAll();
        c.add(i);
        c.revalidate();
        c.repaint();
    }

    private void Image(String URL, JLabel l, int ancho, int alto) {
        Image j = Toolkit.getDefaultToolkit().getImage(getClass().getResource(URL));
        l.setIcon(new ImageIcon(j.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atras = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jack = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        f = new javax.swing.JLabel();
        f1 = new javax.swing.JLabel();
        fs = new javax.swing.JLabel();
        f2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(149, 184, 246));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atras.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        atras.setText("<");
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasMouseClicked(evt);
            }
        });
        add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 50, 50));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("de responder mal obtienes 2 puntos  y  si omites la pregunta 0 puntos");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 940, 30));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tienes una ronda de 5 preguntas por cada acierto ganas 5 puntos en caso  ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 940, 30));

        jack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jack, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 200, 280));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(250, 95, 73));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Modo de juego");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 60));

        f.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        f.setForeground(new java.awt.Color(255, 255, 255));
        f.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f.setText("Modo");
        f.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        f.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        f.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fMouseClicked(evt);
            }
        });
        add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 290, 190));

        f1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        f1.setForeground(new java.awt.Color(255, 255, 255));
        f1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f1.setText("Seleccionar");
        f1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        f1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 290, 200));

        fs.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        fs.setForeground(new java.awt.Color(255, 255, 255));
        fs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fs.setText("Modo");
        fs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fsMouseClicked(evt);
            }
        });
        add(fs, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 290, 190));

        f2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        f2.setForeground(new java.awt.Color(255, 255, 255));
        f2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f2.setText("Poner");
        f2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        f2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 290, 210));
    }// </editor-fold>//GEN-END:initComponents

    private void atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseClicked
        Inicio i = new Inicio(c);
        page(i, c);
    }//GEN-LAST:event_atrasMouseClicked

    private void fMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fMouseClicked
        Juego.getInstancia().setTipoJuego(0);
        Juego.getInstancia().iniciarGame();
        ModoSelecionar ms = new ModoSelecionar(c);
        page(ms, c);
    }//GEN-LAST:event_fMouseClicked

    private void fsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fsMouseClicked
        // TODO add your handling code here:
        Juego.getInstancia().setTipoJuego(1);
        Juego.getInstancia().iniciarGame();
        ModoPoner mp = new ModoPoner(c);
        page(mp, c);
        
    }//GEN-LAST:event_fsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atras;
    private javax.swing.JLabel f;
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel fs;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jack;
    // End of variables declaration//GEN-END:variables
}
