/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import metodos.Juego;
import metodos.Problema;

/**
 *
 * @author Josue
 */
public class ModoSelecionar extends javax.swing.JPanel {

    /**
     * Creates new form ModoSelecionar
     */
    private final JPanel c;
    private Problema problema;
    private int correcto;

    public ModoSelecionar(JPanel c) {
        initComponents();
        this.c = c;

        Image("/img/006.png", jack, 400, 400);

        Image("/img/008.png", f1, 60, 60);
        Image("/img/008.png", f2, 60, 60);
        Image("/img/008.png", f3, 60, 60);
        
        cargarProblema();
    }
    
    public void cargarProblema() {
        problema = Juego.getInstancia().nextProblema();

        sumando1.setText(problema.getSumando1() + "");
        sumando2.setText("?");
        operador.setText(problema.getOperandor() + "");
        respuesta.setText(problema.getRespuesta() + "");

        JLabel posibles[] = {posible1, posible2, posible3};
        correcto = Problema.getAleatorio(posibles.length);
        for (int i = 0; i < posibles.length; i++) {
            if (correcto == i) {
                posibles[i].setText(problema.getSumando2() + "");
            } else {
                posibles[i].setText(Problema.getAleatorio(10) + "");
            }
        }

        numProblema.setText(Juego.getInstancia().getProblemaActual() + "");
        ctdadDePuntos.setText(Juego.getInstancia().getPuntos() + "");
    }

    public void ComenzarJuego() {
        Juego juego = new Juego();
        int n = juego.getProblemasDeTipoSeleccion().size();
    }

    public int Random() {
        return (int) ((100) * Math.random());
    }

    private void PosSelecion() {
        Image("/img/005.png", jack, 400, 400);
    }

    private void DesSelecion() {
        Image("/img/006.png", jack, 400, 400);
    }

    private void Image(String URL, JLabel l, int ancho, int alto) {
        Image j = Toolkit.getDefaultToolkit().getImage(getClass().getResource(URL));
        l.setIcon(new ImageIcon(j.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH)));
    }

    private void page(JPanel i, JPanel c) {
        i.setSize(c.getWidth(), c.getHeight());
        i.setLocation(0, 0);

        c.removeAll();
        c.add(i);
        c.revalidate();
        c.repaint();
    }

    private void evaluar(int seleccion) {
        if (correcto == seleccion) {
            abrirCorrectoPag();
        } else {
            abrirIncorrectoPag();
        }
    }

    private void abrirCorrectoPag() {
        Juego.getInstancia().SistemaDePuntos(5);
        Acierto a = new Acierto(c);
        page(a, c);
    }

    private void abrirIncorrectoPag() {
        Juego.getInstancia().SistemaDePuntos(2);    
        Fallo f = new Fallo(c);
        page(f, c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        posible1 = new javax.swing.JLabel();
        posible2 = new javax.swing.JLabel();
        posible3 = new javax.swing.JLabel();
        tiempo1 = new javax.swing.JLabel();
        respuesta = new javax.swing.JLabel();
        ctdadDePuntos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        operador = new javax.swing.JLabel();
        jack = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sumando2 = new javax.swing.JLabel();
        sumando1 = new javax.swing.JLabel();
        f2 = new javax.swing.JLabel();
        f3 = new javax.swing.JLabel();
        omitir = new javax.swing.JLabel();
        f1 = new javax.swing.JLabel();
        numProblema = new javax.swing.JLabel();
        tiempo3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(149, 184, 246));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        posible1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        posible1.setForeground(new java.awt.Color(255, 255, 255));
        posible1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posible1.setText("5");
        posible1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                posible1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                posible1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                posible1MouseExited(evt);
            }
        });
        add(posible1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 80, 60));

        posible2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        posible2.setForeground(new java.awt.Color(255, 255, 255));
        posible2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posible2.setText("4");
        posible2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                posible2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                posible2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                posible2MouseExited(evt);
            }
        });
        add(posible2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 80, 60));

        posible3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        posible3.setForeground(new java.awt.Color(255, 255, 255));
        posible3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posible3.setText("8");
        posible3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                posible3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                posible3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                posible3MouseExited(evt);
            }
        });
        add(posible3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 80, 60));

        tiempo1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        tiempo1.setForeground(new java.awt.Color(255, 255, 255));
        tiempo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiempo1.setText("Selecione la respuesta correcta");
        add(tiempo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 580, 70));

        respuesta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        respuesta.setForeground(new java.awt.Color(255, 255, 255));
        respuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        respuesta.setText("10");
        add(respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 80, 60));

        ctdadDePuntos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        ctdadDePuntos.setForeground(new java.awt.Color(255, 255, 255));
        ctdadDePuntos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ctdadDePuntos.setText("0");
        add(ctdadDePuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 80, 60));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("salir");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 100, 60));

        operador.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        operador.setForeground(new java.awt.Color(255, 255, 255));
        operador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        operador.setText("+");
        add(operador, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 80, 60));

        jack.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jack.setForeground(new java.awt.Color(255, 255, 255));
        jack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 240, 370));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("=");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 80, 60));

        sumando2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        sumando2.setForeground(new java.awt.Color(255, 255, 255));
        sumando2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sumando2.setText("?");
        add(sumando2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 80, 60));

        sumando1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        sumando1.setForeground(new java.awt.Color(255, 255, 255));
        sumando1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sumando1.setText("5");
        add(sumando1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 80, 60));

        f2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        f2.setForeground(new java.awt.Color(255, 255, 255));
        f2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 80, 60));

        f3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        f3.setForeground(new java.awt.Color(255, 255, 255));
        f3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 80, 60));

        omitir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        omitir.setForeground(new java.awt.Color(255, 255, 255));
        omitir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        omitir.setText("omitir");
        omitir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                omitirMouseClicked(evt);
            }
        });
        add(omitir, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 100, 60));

        f1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        f1.setForeground(new java.awt.Color(255, 255, 255));
        f1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 80, 60));

        numProblema.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        numProblema.setForeground(new java.awt.Color(255, 255, 255));
        numProblema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numProblema.setText("25");
        add(numProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 120, 70));

        tiempo3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tiempo3.setForeground(new java.awt.Color(255, 255, 255));
        tiempo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiempo3.setText("Puntos :");
        add(tiempo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 120, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void posible1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posible1MouseEntered
        PosSelecion();
    }//GEN-LAST:event_posible1MouseEntered

    private void posible1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posible1MouseExited
        DesSelecion();
    }//GEN-LAST:event_posible1MouseExited

    private void posible2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posible2MouseEntered
        PosSelecion();
    }//GEN-LAST:event_posible2MouseEntered

    private void posible2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posible2MouseExited
        DesSelecion();
    }//GEN-LAST:event_posible2MouseExited

    private void posible3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posible3MouseEntered
        PosSelecion();
    }//GEN-LAST:event_posible3MouseEntered

    private void posible3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posible3MouseExited
        DesSelecion();
    }//GEN-LAST:event_posible3MouseExited

    private void posible1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posible1MouseClicked
        evaluar(0);
    }//GEN-LAST:event_posible1MouseClicked

    private void posible2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posible2MouseClicked
        evaluar(1);
    }//GEN-LAST:event_posible2MouseClicked

    private void posible3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posible3MouseClicked
        evaluar(2);
    }//GEN-LAST:event_posible3MouseClicked

    private void omitirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_omitirMouseClicked
        if (!Juego.getInstancia().isJuegoTerminado()) {
            cargarProblema();
        } else {
            Juego.getInstancia().terminarJuego();
            ModoRanking m = new ModoRanking(c);
            page(m, c);
        }
    }//GEN-LAST:event_omitirMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        ModoDeJuego j = new ModoDeJuego(c);
        page(j, c);
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ctdadDePuntos;
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel f3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jack;
    private javax.swing.JLabel numProblema;
    private javax.swing.JLabel omitir;
    private javax.swing.JLabel operador;
    private javax.swing.JLabel posible1;
    private javax.swing.JLabel posible2;
    private javax.swing.JLabel posible3;
    private javax.swing.JLabel respuesta;
    private javax.swing.JLabel sumando1;
    private javax.swing.JLabel sumando2;
    private javax.swing.JLabel tiempo1;
    private javax.swing.JLabel tiempo3;
    // End of variables declaration//GEN-END:variables
}
